apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "generic-app.fullname" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "generic-app.name" . } }
  template:
    metadata:
      labels:
        app: { { include "generic-app.name" . } }
    spec:
      containers:
        - name: { { include "generic-app.name" . } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.port } }
          livenessProbe:
            httpGet:
              path: { { .Values.livenessProbe.path } }
              port: { { .Values.livenessProbe.port } }
            initialDelaySeconds:
              { { .Values.livenessProbe.initialDelaySeconds } }
            periodSeconds: { { .Values.livenessProbe.periodSeconds } }
          readinessProbe:
            httpGet:
              path: { { .Values.readinessProbe.path } }
              port: { { .Values.readinessProbe.port } }
            initialDelaySeconds:
              { { .Values.readinessProbe.initialDelaySeconds } }
            periodSeconds: { { .Values.readinessProbe.periodSeconds } }
          resources: { { - toYaml .Values.resources | nindent 12 } }
