replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

pdb:
  enabled: true
  minAvailable: 1

livenessProbe:
  path: /
  port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  path: /
  port: http
  initialDelaySeconds: 5
  periodSeconds: 5
